### ISSUE TITLE
Configure EditorConfig

### ISSUE THREAD

**Issue by yxqsnz** [Coders-Community-BR/CodersGoBot#1]
see: https://editorconfig.org/
Questions:
 

- [ ] Use tab or spaces?
- [ ] Tab size?

**Comment by yxqsnz** [comment]
cc: @GaahDias @Sigmw

**Comment by Gorniaky** [comment]
guides casually bug with me

**Comment by yxqsnz** [comment]
> guides casually bug with me 2 spaces is better

same as @gabrielkinash1?

**Comment by GaahDias** [comment]
We discussed that in our discord chat, and came to an agreement in 2 spaces.
