### ISSUE TITLE
Logs excessivos

### ISSUE THREAD

**Issue by GaahDias** [Coders-Community-BR/CodersGoBot#24]
O bot está produzindo muitos logs de warn. Alguma ideia da razão disso @yxqsnz ?
![image](https://user-images.githubusercontent.com/36492293/176974963-346290d1-05f7-4fe7-993d-4e3f98a6c34a.png)

**Comment by yxqsnz** [comment]
É os logs de aviso do discordgo(Eu não recomendaria desativar). 
Mas caso você queira desativar é só comentar a linha abaixo 
https://github.com/Coders-Community-BR/CodersGoBot/blob/3b9a428037820ee11794f437e122a378081849d1/main.go#L45

**Comment by yxqsnz** [comment]
#29
